//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentApp.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentEntities : DbContext
    {
        public RentEntities()
            : base("name=RentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<branch> branch { get; set; }
        public virtual DbSet<pictureconfirmation> pictureconfirmation { get; set; }
        public virtual DbSet<rating> rating { get; set; }
        public virtual DbSet<reservation> reservation { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<vehicle> vehicle { get; set; }
        public virtual DbSet<vehicletype> vehicletype { get; set; }
    }
}
