//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int id { get; set; }
        public Nullable<System.DateTime> timestart { get; set; }
        public Nullable<System.DateTime> timeend { get; set; }
        public int user_id { get; set; }
        public int vehicle_id { get; set; }
        public int branch_id1 { get; set; }
        public int branch_id { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual branch branch1 { get; set; }
        public virtual user user { get; set; }
        public virtual vehicle vehicle { get; set; }
    }
}
