//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicle()
        {
            this.reservation = new HashSet<reservation>();
        }
    
        public int id { get; set; }
        public string model { get; set; }
        public string manufacturer { get; set; }
        public Nullable<int> year { get; set; }
        public string pictureurl { get; set; }
        public string description { get; set; }
        public Nullable<int> branch_id { get; set; }
        public int vehicletype_id { get; set; }
    
        public virtual branch branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservation { get; set; }
        public virtual vehicletype vehicletype { get; set; }
    }
}
